from google import genai
from google.genai import types
from config.settings import config
from typing import Optional

class VertexAIClient:
    """
    Client to interact with Vertex AI models using the new google-genai SDK.
    """

    def __init__(self):
        """
        Initializes the connection with Vertex AI.
        """
        # Initialization for Vertex AI (vertexai=True)
        self.client = genai.Client(
            vertexai=True,
            project=config.PROJECT_ID,
            location=config.LOCATION
        )
        self.model_name = config.MODEL_NAME

    def analyze_pdf_content(self, gcs_uri: str, prompt_text: str) -> Optional[str]:
        """
        Send a PDF file (referenced in GCS) and a prompt to the model.

        Args:
            gcs_uri (str): File URI in GCS (e.g. gs://bucket/archivo.pdf).
            prompt_text (str): Prompt for the model.

        Returns:
            Optional[str]: Text response generated by the model or None if it fails.
        """
        try:
            # Create the content part for the PDF
            pdf_part = types.Part.from_uri(
                file_uri=gcs_uri,
                mime_type="application/pdf"
            )
            
            text_part = types.Part.from_text(text=prompt_text)

            # Configuration
            generation_config = types.GenerateContentConfig(
                max_output_tokens=8192,
                temperature=0.2, # Bajo para respuestas más deterministas y técnicas
                top_p=0.95,
            )

            # Generate content
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=[
                    types.Content(
                        role="user",
                        parts=[pdf_part, text_part]
                    )
                ],
                config=generation_config
            )

            return response.text
        except Exception as e:
            print(f"Error calling Vertex AI (google-genai): {e}")
            return None